apiVersion: v1
kind: Service
metadata:
  name: velocity-backend-svc
  namespace: velocity-namespace
  labels:
    app: velocity-engine
    component: backend-go
spec:
  type: ClusterIP
  selector:
    app: velocity-engine
    component: backend-go
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
